# Generated by Django 2.0.7 on 2018-08-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibrate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adminStaff',
            field=models.BooleanField(default=False),
        ),
    ]
